### ISSUE TITLE
no-url example is not doing the animation after uploading

### ISSUE THREAD

**Issue by jey9711** [felixrieseberg/React-Dropzone-Component#101]
the animation when it finishes uploading doesn't work! I ran the example locally too and it doesn't show the tick animation.

PS: i had to manually npm install 5 things first for the example to work.

Would be great if you can get back to me asap. Thanks so much and hope your monday is going great!

**Comment by optyler** [comment]
> PS: i had to manually npm install 5 things first for the example to work.

Could you put them here, for other while this is not fixed?
