### ISSUE TITLE
Flux example

### ISSUE THREAD

**Issue by minimaximus** [felixrieseberg/React-Dropzone-Component#11]
Hi,

It would be really helpful to provide a simple Flux example where the user drops the files, then clicks upload to send them to the server.  How hard is it to accomplish this? I'd be willing to help on that if you give me some pointers.  Like how do I call processQueue() given that I don't have access to that method directly from your component.

Thanks,

minimaximus

**Comment by erikschlegel** [comment]
I pushed out a fix and re-published to NPM which should resolve the issue. I'll leave this open til end of day, just in case you run into any other problems. 

Thanks for pointing this out and apologies for any frustration this caused.

Erik

**Comment by felixrieseberg** [comment]
Hey,

I'm not a heavy Flux user, so I probably wouldn't provide the best example - any and all help is very welcome! To access `processQueue`, simply provide a handler for the `init` event, which has the `dropzone` as its parameter (https://github.com/felixrieseberg/React-Dropzone-Component#callbacks).

```JS
var eventHandlers = {
    init: function (dropzone) {
        // dropzone.processQueue()
    }
}

React.render(
    <DropzoneComponent config={componentConfig} 
                       eventHandlers={eventHandlers} 
                       djsConfig={djsConfig} />, 
    document.getElementById('content')
);
```

**Comment by minimaximus** [comment]
Hi Felix,

thanks for the response.  The problem with this approach is that I need processQueue() to be called in response to a button click, so having it called in init() wouldn't help.  I rebuilt your plugin and exposed an upload() method that internally calls the processQueue() function, which seems to work as intended.

**Comment by felixrieseberg** [comment]
Oh, you can just use the init method to set a `dropzone` variable, like so:

```JS
var dropzone;

var eventHandlers = {
    init: function (passedDropzone) {
        dropzone = passedDropzone
    }
}

document.getElementById('myButton').onClick(function () {
    if (dropzone) {
        dropzone.processQueue();
    }
});
```

I'm closing this in the meantime, but feel free to ask more questions!
