### ISSUE TITLE
Implementing S3 upload from client

### ISSUE THREAD

**Issue by rajankarthiks** [felixrieseberg/React-Dropzone-Component#110]
Hi,

Could you please help with this component to upload directly to s3? could you provide an example or can you guide me in integrating this? I am stuck.

**Comment by ko** [comment]
I'm not entirely familiar with using Amazon S3 in detail. 

With that said, have you seen [this document](http://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTForms.html)? The ```form action``` referenced should be what you use as the ```postUrl``` value for the component config.
