### ISSUE TITLE
Non-accessible methods

### ISSUE THREAD

**Issue by HectorIFC** [felixrieseberg/React-Dropzone-Component#112]
###  How to access  myDropzone.removeAllFiles( )  and myDropzone.removeAllFiles(true) methods ? I want to use a button

**Comment by ko** [comment]
If you define a ```this.dropzone``` as [seen here](https://github.com/felixrieseberg/React-Dropzone-Component/blob/master/example/src/example_default.jsx#L33) and initialized [here](https://github.com/felixrieseberg/React-Dropzone-Component/blob/master/example/src/example_default.jsx#L42), are you able to access ```this.dropzone.removeAllFiles()``` from your button's click handler?

**Comment by HectorIFC** [comment]
will try. thanks for the tips.

**Comment by HectorIFC** [comment]
@ko  thanks.  its working. Fell like a glove. The translation is right I think... kk

**Comment by ko** [comment]
Nice!

**Comment by BKD-Digital** [comment]
feel free to close this issue ;)

**Comment by HectorIFC** [comment]
ok.
