### ISSUE TITLE
Upload Server

### ISSUE THREAD

**Issue by rajapulau** [felixrieseberg/React-Dropzone-Component#12]
hello,

why my Request Method:OPTIONS .. how can i replace with POST??

for example my url upload : http://example.com/upload.php

**Comment by felixrieseberg** [comment]
Hey, I'm not sure I understand your question?

**Comment by rajapulau** [comment]
i can explain you with code, for example:
var componentConfig = {
    allowedFiletypes: ['.jpg', '.png', '.gif'],
    showFiletypeIcon: true,
    postUrl: 'https://example.com/upload.php?username=xxx&id=115&hashing=ok'
};

On your example request method using POST
![cors2](https://cloud.githubusercontent.com/assets/958302/8219810/d7692b62-1576-11e5-98e8-5470910c6312.png)

But on my code request method using OPTIONS
![cors](https://cloud.githubusercontent.com/assets/958302/8219818/e31d2030-1576-11e5-83e8-88569fac189f.png)

**Comment by felixrieseberg** [comment]
Oh, I see! That's a cross-domain security feature in jQuery / Dropzone. More information is available here: http://stackoverflow.com/questions/1256593/jquery-why-am-i-getting-an-options-request-instead-of-a-get-request.

That's actually not an issue with this component, but with XSS, so I'm closing this for now. The thread linked should tell you everything you need :)

**Comment by rajapulau** [comment]
oke felix thank you.. you can close this issue
