### ISSUE TITLE
Preview template as React component

### ISSUE THREAD

**Issue by jonashagstedt** [felixrieseberg/React-Dropzone-Component#13]
Is it possible to have the preview template as a React component?

       var ImagePreview = React.createClass({
            deleteImage: function () {
                // delete the image
            },
            
            render: function () {
                return <img src={this.props.imageUrl} onClick={this.deleteImage} />
            }
        });

        // and in the actual component using the <DropzoneComponent />
        ...
        var djsConfig = {
            previewTemplate: ImagePreview
        };

other than that, this is so far the best image uploader for React I've found!

**Comment by jonashagstedt** [comment]
Actually this is not that important. The `complete` callback can be used to render previews, and the original previews can be removed by simply rendering an empty `<span/>` in there.

Feel free to close this issue if you want to

**Comment by felixrieseberg** [comment]
Hey! Since DropzoneJS manages the preview template itself, you can't submit a live and breathing React Element, but you can use the `previewTemplate` property in `djsConfig` to pass the component a template. If you use `React.renderToStaticMarkup`, that can even be a React element - it's just static from the moment DropzoneJS takes over.

Does that make sense?

```JSX
var djsConfig = {
  previewTemplate: React.renderToStaticMarkup(
    <div className="dz-preview dz-file-preview">
      <div className="dz-details">
        <div className="dz-filename"><span data-dz-name></span></div>
        <img data-dz-thumbnail />
      </div>
      <div className="dz-progress"><span className="dz-upload" data-dz-uploadprogress></span></div>
      <div className="dz-success-mark"><span>✔</span></div>
      <div className="dz-error-mark"><span>✘</span></div>
      <div className="dz-error-message"><span data-dz-errormessage></span></div>
    </div>
  )
}
```

**Comment by jonashagstedt** [comment]
I don't think my React skills are good enough but I suspect that if you do that you wouldn't be able to use the events in a React component and you wouldn't get any properties related to the image.

It's not a biggie though as you can simply create new React elements in the `complete` callback where you'll have the image data available.

**Comment by cjke** [comment]
I realised this is nearly a year old - but @felixrieseberg - just curious if the example above is intended to work with click events?

I have bootstrapped a basic example, and it seems that `renderToStaticMarkup` strips onClick events from the generated mark up. 

Thanks for the work on the library

**Comment by felixrieseberg** [comment]
Yep, sorry - that is indeed what that means (and I realize that your comment is ancient too, but I thought I'd leave it here anyways).

**Comment by cjke** [comment]
Thanks @felixrieseberg !

**Comment by rohitRev** [comment]
I want to make the preview Clickable  . what i exactly want to do is i want to open a popup on the click of preview .. can u please suggest me code snippet for that ?

**Comment by rohitRev** [comment]
You can add addEventListener to onDrop or OnComplete event , In this function you will get array record of uploaded files

**Comment by djmrky** [comment]
Hello,

I'm also looking for a way to click somewhere in the dropzone which already contains some documents (PDF-files) so I can get which file was clicked and show the preview in another component (PDF Viewer)

Can somebody help?

**Comment by appdeveloperhw** [comment]
I know it's too late but hope it will help someone. I managed to click and get value adding custom tag with class **Someclass** in **previewTemplate** and then on **addedfile** access like file.previewElement.querySelector(".Someclass")

the code example is 

component in render 


```
<DropzoneComponent
              config={dropzoneComponentConfig}
              djsConfig={dropzoneConfig}
              eventHandlers={{ addedfile: this.fileHandler }}
              />
```

and event handler function 


```
fileHandler = (file) => {
        var element = file.previewElement.querySelector(".Someclass")
        element.onclick = function () { alert("") };
 }
```


and in **dropzoneConfig**  the **previewTemplate** as


```
previewTemplate: ReactDOMServer.renderToStaticMarkup (
         <div className="dz-preview dz-file-preview mb-3">
               ....
              <a href="#/" className="Someclass">
              </a>
         </div>
)
```
