### ISSUE TITLE
I can upload only 2 images to server then hang  how to fix 

### ISSUE THREAD

**Issue by lagmanzaza** [felixrieseberg/React-Dropzone-Component#130]
I'm sorry , I'm bad english 

I set autoprocess = false

**Comment by lagmanzaza** [comment]
I can fix it

**Comment by ettaibi** [comment]
I have same issue, only 2 images are uploaded when i set autoprocess = false

**Comment by lagmanzaza** [comment]
I set value in parallelUpload  option its more than 2

_Sent from my Samsung SM-J510FN using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
