### ISSUE TITLE
 Leaving postUrl blank throws error

### ISSUE THREAD

**Issue by jasecoop** [felixrieseberg/React-Dropzone-Component#15]
Firstly, thanks for this, very useful. Though I've run into the following problem.

I'm using Parse so I'd like to handle the file upload myself rather than go through postUrl.

As suggested:

> Usage Without Automatic Posting
>
> If you want to use this component without posting automatically to a URL but instead do the posting yourself, then you can just leave the postUrl option empty and handle the displaying of progress by yourself using the provided event handlers.

Though when I leave postUrl I recieve the following error:

Uncaught Error: No URL provided.

Any thoughts how I can work around this?

**Comment by felixrieseberg** [comment]
Hey @jasecoop! That's actually not an error with this implementation of Dropzone, but Dropzone itself. It's easy to fix though: Dropzone will be fine with you not having a URL if you wrap it in a `<form></form>` element. Are you using one? If not, I could try to see if we have an error here.

**Comment by jasecoop** [comment]
@felixrieseberg Thanks, Felix. I thought it might be a result of Dropzone.

My Dropzone is actually on the body, so there's no form.

Any thoughts how I can get round this?

**Comment by felixrieseberg** [comment]
If you've done everything right - and you really don't want to put it into a form - a small change I just pushed (4.0.2) should help you out, as it disables  Dropzone's autodiscover feature.

**Comment by mtando** [comment]
Hi Felix, i still got this issue using React-Dropzone-Component v 0.4.4.. could you please advise? Thanks

**Comment by felixrieseberg** [comment]
Well, we'll reopen the issue, that's for sure ;-) Let me give it a try - I'll report back.

**Comment by appshore** [comment]
Same issue here and the Dropzone component is in a <form>.

Uncaught Error: No URL provided.Dropzone 
@ app.browserify.js?a2f755f9927317c268cf4a67a22e62a209b218cd:736React.createClass.componentDidMount 
@ app.browserify.js?a2f755f9927317c268cf4a67a22e62a209b218cd:61assign.notifyAll 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:1079ON_DOM_READY_QUEUEING.close 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:14624Mixin.closeAll 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:18677Mixin.perform 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:18618batchedMountComponentIntoNode 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:12564Mixin.perform 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:18604ReactDefaultBatchingStrategy.batchedUpdates 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:9612batchedUpdates 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:16619ReactMount._renderNewRootComponent 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:12699ReactPerf.measure.wrapper 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:13941ReactMount.render 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:12788ReactPerf.measure.wrapper 
@ react.browserify.js?345ed1d2c9fb8e823a80b4ddddc390a5a28d2b87:13941(anonymous function) @ react_layout.js:42jQuery.Callbacks.fire 
@ jquery.js:3143jQuery.Callbacks.self.fireWith 
@ jquery.js:3255jQuery.extend.ready 
@ jquery.js:3467completed

**Comment by felixrieseberg** [comment]
Hey everybody, thanks for waiting - I know finally have it figured out. Dropzone.js requires that the Dropzone element is a `<form>` with the `action` attribute set - that's why y'all ran into errors. I just pushed an update (0.5.0) that is capable of doing just that. To use, use the component like so:

```JS
var componentConfigWithoutPostUrl = {
    allowedFiletypes: ['.jpg', '.png', '.gif'],
    showFiletypeIcon: true,
};
React.render(
    <DropzoneComponent config={componentConfigWithoutPostUrl} 
                       eventHandlers={eventHandlers}
                       action="post.php"
                       djsConfig={djsConfig} />, 
    document.getElementById('content')
);
```

I will be closing this in the meantime. Thanks to @appshore, @jasecoop and @mtando for reporting, you rock!

**Comment by kand617** [comment]
Hello,

I have issues. I believe I have followed what was shown.
Adding the action ends up invoking the http call.....

This what I have 

```
getFileInput(){
    var componentConfig = {
      iconFiletypes: ['.jpg', '.png', '.gif'],
      showFiletypeIcon: true
      // Notice how there's no postUrl set here
    };
    var handlers = {
      drop:this.fileDropped
      // Notice how there's no postUrl set here
    };
    // Add params to your dropzonejs configuration object, like so:
    var djsConfig = {
        addRemoveLinks: true,
        
    };


     return <DropzoneComponent 
     config={componentConfig} 
     eventHandlers={handlers} 
      action="post.php"
     djsConfig={djsConfig}


    />
  }
```

It renders fine, but once I hover over it I get this
![upload error](https://cloud.githubusercontent.com/assets/5092518/12535430/1eaffdf6-c2e8-11e5-9de8-405476dd5391.PNG)

With the console message:
POST http://localhost:8000/post.php 404 (Not Found)

**Comment by qiuwei** [comment]
There is a side effect of having action attribute in the Dropzone Component, the component doesn't pick up the css styles anymore.

**Comment by mrpatiwi** [comment]
I'm having the error as @kand617, it's automatically POSTing when I don't want to.
