### ISSUE TITLE
there is no styles after import this component

### ISSUE THREAD

**Issue by joriewong** [felixrieseberg/React-Dropzone-Component#162]
- HTML
![tim 20180411160128](https://user-images.githubusercontent.com/11408040/38604022-c506262c-3da1-11e8-95b2-fd6b0cf98bc8.png)
- View
![tim 20180411160151](https://user-images.githubusercontent.com/11408040/38604034-cef3c7ac-3da1-11e8-8521-7a769172f35c.png)

**Comment by joriewong** [comment]
```html
<link rel="stylesheet" href="node_modules/react-dropzone-component/styles/filepicker.css">
<link rel="stylesheet" href="node_modules/dropzone/dist/min/dropzone.min.css">
```

**Comment by MattSidor** [comment]
Here's how to do it with `import` statements:

    import DropzoneComponent from 'react-dropzone-component';

    import 'react-dropzone-component/styles/filepicker.css';
    import 'dropzone/dist/dropzone.css';`
