### ISSUE TITLE
Drag and Drop from Body HTML

### ISSUE THREAD

**Issue by rajapulau** [felixrieseberg/React-Dropzone-Component#17]
Hi Felix,
where the setting how to upload drang and drop from body? form example from Dropzone

```
new Dropzone(document.body, { // Make the whole body a dropzone
    url: "/upload/url", // Set the url
    previewsContainer: "#previews", // Define the container to display the previews
    clickable: "#clickable" // Define the element that should be used as click trigger to select files.
  });
```

**Comment by felixrieseberg** [comment]
Hey! I'm not sure that this component is perfect for the use case - you'd probably be better off with just using dropzone, since you don't want a dropzone element. I'll close this in the meantime, let me know if you have any other questions!
