### ISSUE TITLE
HEVC codec support (iPhoneX)

### ISSUE THREAD

**Issue by braime** [felixrieseberg/React-Dropzone-Component#175]
I am having "fun" with Apples new video codec HEVC/h265 and am VERY surprised, that nobody else has any issues with this codec. In our application, we use a mobile device to record video (or choose from the phones mediathek) and then send it to another computer for playback (in a browser as HTML5 video).

The problem we are facing is a different result, weather I choose a video from the phones mediathek versus recording the video live. If I record a video with the native iOS camera app, then choose this video inside our app from the phones mediathek, everything works quite fine and the video is encoded with h264. But if I record the video directly inside our app, the video is encoded with HEVC/h265 instead of h264!!! Result in Chrome, stillframe of first image and only audiostream is playing... 

<img width="820" alt="bildschirmfoto 2018-07-02 um 14 54 46" src="https://user-images.githubusercontent.com/6401345/42165243-fa6230d0-7e07-11e8-82c4-1f50ea98bca6.png">

I even do not know exactly, what the solution would be, other than converting h265 to h264... Why do other users not face this issue? Am I overseeing something trivial? Please let me know, if you need more information, I am happy for any hint or comment!

Thanks so much in advance!!!

EDIT:
At least a similar Stackoverflow post:
https://stackoverflow.com/questions/51103054/html-input-file-video-iphone-x-codec-issue

**Comment by 0x111** [comment]
Maybe I just don't understand what you've wrote here, but I don't think this has any relation to this component as such, this only wraps the dropzonejs for it to be used in React. If I'm mistaken maybe someone will correct me.

**Comment by braime** [comment]
Hi there, sorry for the late response and inability to describe the problem properly. I think this issue can be closed. It still persists in our project, but as no other user seems to have similar issues, the false behaviour has to be somewhere else in our stack. Currently there is no time to investigate this problem in more depth, if it would really be inside your wrapper, I would reopen the issue. Thanks either way!
