### ISSUE TITLE
Server-side rendering with .NET

### ISSUE THREAD

**Issue by gregbty** [felixrieseberg/React-Dropzone-Component#18]
I've tried to render the component on the server but it doesn't work properly, because it requires the window object.

```javascript
contentLoaded(window, Dropzone._autoDiscoverFunction);
```

The quoted line is causing the issue. I tried faking an empty window object but then it attempts to use other browser dom specific constructs. Is possible to attach the dom specific handlers only when the window object is present or is there any other workaround?

**Comment by felixrieseberg** [comment]
Hm, I'm actually not sure that Dropzone.js works without the window object. If there's something we can change in this module, I'd be happy to do that though - any ideas?

**Comment by gregbty** [comment]
I'll see if I can come up with something. Maybe I can think of a better way to only render it client side.

**Comment by tomchentw** [comment]
Encounter same issue with node.js rendering here. I think the best way to do it is only `require('dropzone')` inside `DropzoneComponent#componentDidMount`

**Comment by tomchentw** [comment]
Some one had forked it like this:
https://github.com/cainvommars/React-Dropzone-Component/commit/8f5b9922036ad247bd3698cd11cf0b9259f280f2

**Comment by felixrieseberg** [comment]
Huh, cool. I'll take a look at this - sounds like it would be a good thing to do even if you're rendering on the client.
