### ISSUE TITLE
NPM Version doesn't have latest commit.

### ISSUE THREAD

**Issue by connorjburton** [felixrieseberg/React-Dropzone-Component#19]
I have done

    npm i react-dropzone-component

And when I view

    /lib/dropzone.js

The commit that resolves the Key warning doesn't exist. The line still shows

    icons.push(React.createElement(IconComponent, {filetype: this.props.config.allowedFiletypes[i]}));

**Comment by felixrieseberg** [comment]
Thanks, I'll fix that right away!
