### ISSUE TITLE
Only two files are being uploaded but i want to upload more than that

### ISSUE THREAD

**Issue by TaurahSP** [felixrieseberg/React-Dropzone-Component#190]

**Comment by 0x111** [comment]
Can you provide any example of your problem? Seems to me that it is a configuration issue probably.

**Comment by mleray** [comment]
Hi, any updates/tips on this? I'm having the same issue...

**Comment by DanielRuf** [comment]
> Hi, any updates/tips on this? I'm having the same issue...

Please open a new issue with a small reproducible testcase.
