### ISSUE TITLE
React 16 migration (lifecycle methods)

### ISSUE THREAD

**Issue by DanielRuf** [felixrieseberg/React-Dropzone-Component#205]
In React 16 a few lifecycle methods are deprecated and marked as unsafe. We should test on multiple react and react-dom versions and try to support the latest React release.

**Comment by rgdevment** [comment]
https://github.com/felixrieseberg/React-Dropzone-Component/pull/212

When you can, please check this

**Comment by BastianMa** [comment]
React 17 is coming. This component will not work anymore if this issue will not be fixed

**Comment by DanielRuf** [comment]
> React 17 is coming. This component will not work anymore if this issue will not be fixed

Afaik you can use older React versions in newer React versions (starting with React 17 with the gradual updates feature).
https://reactjs.org/blog/2020/08/10/react-v17-rc.html

So you can still get it working.
