### ISSUE TITLE
How can we updated group permissions using PNP

### ISSUE THREAD

**Issue by meet2sujit** [felixrieseberg/React-Dropzone-Component#209]
Need to update group permissions using PNP in react...

**Comment by DanielRuf** [comment]
Hi @meet2sujit,

can you please clarify what you mean?

**Comment by meet2sujit** [comment]
> Hi @meet2sujit,
> 
> can you please clarify what you mean?

Hi I am creating group in SharePoint site using PNP,  after creating we need to set the role/permission as "Contributor" to group. Can you please help me to achieve this functionality.

**Comment by DanielRuf** [comment]
> Hi I am creating group in SharePoint site using PNP, after creating we need to set the role/permission as "Contributor" to group. Can you please help me to achieve this functionality.

How is this related to  React-Dropzone-Component?

**Comment by meet2sujit** [comment]
> > Hi I am creating group in SharePoint site using PNP, after creating we need to set the role/permission as "Contributor" to group. Can you please help me to achieve this functionality.
> 
> How is this related to React-Dropzone-Component?

I am completely new to this git, I was stuck

**Comment by meet2sujit** [comment]
posted in wrong
