### ISSUE TITLE
using dropzone inside form

### ISSUE THREAD

**Issue by ivan9074** [felixrieseberg/React-Dropzone-Component#21]
Hi Felix,

i am new to React and still figuring things out. If you could help me with this issue i have on my mind, i will grateful

I have a form for creating a new item on a queue. This item will have an avatar. So in the form i have all the fields required for the item and the dropzone component to drag and drop images of the item.

the thing is that I want to post everything together to the server, how could i do this? because i saw that if i wanted to do the post myself i had to remove the 'postUrl' property but then i had to add the 'action' prop to the component. So i am a bit confused

Thanks you

**Comment by felixrieseberg** [comment]
Hey Ivan,

it might be best if you consult the documentation for Dropzone.js - it's very good and will contain answers to your question. Basically, if you use `posturl`, the dropzone will upload each image right away, while using a form with a `action` will create a normal HTML form `<form action="upload.php"></form>`. 

Here's my tip: Build a simple upload form that works for you using `action`. Once you have that working, you can replace your `<input>` elements with the React component and everything should still work!

All the best,
Felix
