### ISSUE TITLE
React peer dependency

### ISSUE THREAD

**Issue by arnaud** [felixrieseberg/React-Dropzone-Component#23]
I'm currently using React 0.14.0-beta1 and thus I can't satisfy your peerDependencies requirements.
In fact I get the following error:

> The package react does not satisfy its siblings' peerDependencies requirements!
> Peer react-dropzone-component@0.5.0 wants react@^0.13.0

I hope there is a conventional way for these two to work together?

@felixrieseberg your help is appreciated :pray:

**Comment by felixrieseberg** [comment]
Thanks for reporting! I'll update package.json, should be on npm within the hour :+1:

**Comment by felixrieseberg** [comment]
Aaaaaand fixed. @arnaud thanks again!
