### ISSUE TITLE
How to restrict multiple upload

### ISSUE THREAD

**Issue by sijo-vijayan** [felixrieseberg/React-Dropzone-Component#25]
Hi,
Thanks for making a good plugin like this, I want to restrict multiple uploads from the drop zone,
How can i do it ? I have seen `uploadMultiple` option in your file , but how to use ?

I have tried the following, in the example_default.js file

var componentConfig = {
    allowedFiletypes: ['.jpg', '.png', '.gif'],
    showFiletypeIcon: true,
    uploadMultiple: false,
    maxFiles: 1,
    postUrl: '/uploadHandler'
};

But, It is not working, please help me.

**Comment by sijo-vijayan** [comment]
Finally i find out the solution, We can use `djsConfig` for the same as shown below

	var djsConfig = {
	  maxFiles: 1,
	  paramName: 'profilephoto'
    }

**Comment by felixrieseberg** [comment]
Happy to hear that you found a solution1
