### ISSUE TITLE
Strange cross origin setup

### ISSUE THREAD

**Issue by DennisFrostlander** [felixrieseberg/React-Dropzone-Component#28]
Please remove the Access-Control-Allow-XXX headers from being set on the client. These headers are meant to be returned by the server, not sent by the client. The trouble here is that in cross-origin setup on the server you must explicitly specify the allowed headers, therefore with the default setup you would have to allow Access-Control-Allow headers on the server, which seems a bit strange.

Please also consider setting withCredentials default back to false, as it is in dropzone. Not everybody uses cross-domain authentication, but even if somebody uses it, it's not always cookies. 
The problem with a default setup like this is that if you use withCredentials: true, then on the server side you must explicitly whitelist all allowed domains instead of saying Allow-Origin=*.

**Comment by felixrieseberg** [comment]
That seems reasonable. I'll fix it.

**Comment by bdefore** [comment]
I just ran into this too. Removing all headers and the `withCredentials` flag allowed it to function properly uploading to Cloudinary.

**Comment by bdefore** [comment]
I've made a PR #31 for removing these.
