### ISSUE TITLE
allowedFiletypes causes JS error acceptedFiles.split is not a function

### ISSUE THREAD

**Issue by bdefore** [felixrieseberg/React-Dropzone-Component#32]
I believe dropzone expects a string rather than an array. https://github.com/enyo/dropzone/blob/master/src/dropzone.coffee#L1415

**Comment by felixrieseberg** [comment]
Thanks for the report - I'll fix this in a second!

**Comment by bdefore** [comment]
no problem. i'll verify shortly. thanks for the quick response!
