### ISSUE TITLE
Issue due to DOM changes

### ISSUE THREAD

**Issue by sijo-vijayan** [felixrieseberg/React-Dropzone-Component#38]
Hi,
I'm getting the following error after uploading an image.
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Also i don't want to show any preview of the uploading image.

there is any workaround for this ?

Thanks
SIjo

**Comment by felixrieseberg** [comment]
Hey, quick question - could you check if you still get the same issue with the latest version?

**Comment by sijo-vijayan** [comment]
Hi,
I was used  "react-dropzone-component": "^0.5.3" issue with this version, But after installing the latest version 0.7.0 it showing the following Warning in the browser console and the dropzone stop working.

Warning: React can't find the root component node for data-reactid value `.397iuac3r4.2.2.0.0.4.0.0.2.3.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.

Uncaught TypeError: Cannot read property 'firstChild' of undefined

**Comment by felixrieseberg** [comment]
Just made another pass at the whole thing - it should now be fixed.
