### ISSUE TITLE
Provide clean compiled build without jsx and es6 code

### ISSUE THREAD

**Issue by mbektimirov** [felixrieseberg/React-Dropzone-Component#4]
Requiring node modules shouldn't depend on es6 and jsx transpilers at all. For example here is the part of my webpack config, I am skipping node_modules to make build faster (commonly used practice):
```javascript
module: {
    loaders: [{
      test: /\.(js|jsx)?$/,
      loaders: ['react-hot', 'babel?stage=0'],
      exclude: /node_modules/
    }]
  }
```

**Comment by felixrieseberg** [comment]
Thanks for the request! I made some changes and added built files - let me know if that works for you. 

(I'm closing this in the meantime, but feel free to reopen)

**Comment by mbektimirov** [comment]
Looks like you put all dependencies including React in the final build file. All you need is to generate new files with jsx es6 compiler with the same structure as in `src`. The best way is to put compiled code to `lib` directory before `npm publish` and point `"main"` property to `lib/dropzone.js`. See http://chadly.net/2015/04/publishing-react-to-npm/
