### ISSUE TITLE
Upload url as function

### ISSUE THREAD

**Issue by mvlach** [felixrieseberg/React-Dropzone-Component#42]
Hi,

I would like to use this component but I would like to use Amazon store. So the upload handler is located on variable place (presign url / http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html).

Is there any possibility to call some function and return the URL ? Via callback or promise ?

Thanks Mila

**Comment by mvlach** [comment]
I found some solution but I'm not able do what I need. The function is not async and I need to generate url on server.

**Comment by felixrieseberg** [comment]
Hey, Dropzone actually supports that feature: https://github.com/enyo/dropzone/wiki/Set-URL-dynamically

**Comment by mvlach** [comment]
Hi, this is not what I need. Problem is that generating the URL is async event and can't return the value. I need callback or the promise support. I do some hack and solve this by modifying function done(error, url) in accept callback in dropzone.

If you would like to know more, let me know :)

M.

**Comment by felixrieseberg** [comment]
Hm, sorry about that - I don't think we can do anything about that though, given that we're just wrappen Dropzone here. Have you considered reporting your issue over at Dropzone?

**Comment by mvlach** [comment]
I made some dirty hacks and now I have problem with AWS S3 :)

Sending issue to the Dropzone sounds like good idea...

M.

**Comment by dardub** [comment]
Running into the same issue. Has anyone figured out a good solution?

**Comment by dardub** [comment]
This is what I ended up doing.

`const dropZoneConfig = {
  autoProcessQueue: false,
  init: function () {

    this.on('addedfile', function (file) {

      let _this = this;
      fetch(`${Config.apiBase}/images/cache/presign`).then(function (response) {
        response.json().then(function (json) {
          // Add formdata to param options
          // https://github.com/enyo/dropzone/blob/master/src/dropzone.coffee#L1222
          Object.assign(_this.options.params, json.fields);

          // Update url to s3 endpoint
          _this.options.url = json.url;

          _this.processQueue();
        });
      });
    });
  },
};`

By setting  autoProcessQueue to  false, you can start the upload to s3 process after you fetch the presign data.
