### ISSUE TITLE
Make compatible with rails-assets.org

### ISSUE THREAD

**Issue by tcwalther** [felixrieseberg/React-Dropzone-Component#46]
It would be great if you could make this plugin compatible with rails-assets.org. When trying to add `felixrieseberg/React-Dropzone-Component` at https://rails-assets.org/components/new, it says

    felixrieseberg/React-Dropzone-Component has no versions defined. Please create an issue in component's repository.

**Comment by felixrieseberg** [comment]
Yeah, fair point. Thanks a lot! Will do!

**Comment by felixrieseberg** [comment]
And done, thank you very much!
