### ISSUE TITLE
Integrating this with Rails and Browserify

### ISSUE THREAD

**Issue by kockok** [felixrieseberg/React-Dropzone-Component#5]
I use this code snippet to get started (in dropzone.js.coffee):
```
dropZone = require('react-dropzone-component')
@DropzoneComponent = React.createClass
  render: ->
    React.createElement dropZone
```
(in render html.haml):
```
= react_component 'DropzoneComponent'
```

I just want to test if I installed React-Dropzone-Component correctly, however, it keeps throwing this error:

```
BrowserifyRails::BrowserifyError
events.js:85
      throw er; // Unhandled 'error' event
``` 

Please help.

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! I just changed the bundle method a bit - can you try this again? It should now default to `./lib/dropzone.js` and work.

**Comment by kockok** [comment]
@felixrieseberg looking good, thank you.
