### ISSUE TITLE
add params to headers

### ISSUE THREAD

**Issue by mydearxym** [felixrieseberg/React-Dropzone-Component#51]
amazing work! 

my backend is based on JWT (json web token) ,  it's there a way to add 'Authorization' key in request header ?

**Comment by cgwyllie** [comment]
+1 :)

**Comment by cgwyllie** [comment]
So the Dropzone.js config accepts headers as an option: http://www.dropzonejs.com/#config-headers

I guess the React-Dropzone-Component `config` prop would pass that through to the Dropzone.js underneath?

**Comment by felixrieseberg** [comment]
That should be exactly how it works - does it not work for y'all?

**Comment by mydearxym** [comment]
:+1:  thx for reply @cgwyllie @felixrieseberg

**Comment by ruoguluo** [comment]
Actually I need to put headers in disConfig

**Comment by giancarlobianchi12** [comment]
`djsConfig={{
  headers: {
    Authorization:
      "Bearer " + localStorage.getItem("token"),
  },
}}`
