### ISSUE TITLE
OnMouseOver Event render large image preview

### ISSUE THREAD

**Issue by foodaka** [felixrieseberg/React-Dropzone-Component#55]
Hey Felix loving the plugin, if i want to use an onmouseover event to trigger a larger preview of the image dropped, will i need to config the dropzone js config? tks

http://www.dropzonejs.com/#configuration

**Comment by foodaka** [comment]
edited the dropzone.js file and did a bunch of changes

**Comment by rohitRev** [comment]
Hi foodka  . Can you please tell me same thing to fire click event on preview  ?

Thanks in advance !

**Comment by rohitRev** [comment]
hiii @foodaka  can you please guide me to add click event on  preview div ?

Thanks in Afvance
