### ISSUE TITLE
Add react-dom@^0.14.0 as dependency on npm

### ISSUE THREAD

**Issue by dschoon** [felixrieseberg/React-Dropzone-Component#57]
It'd be really nice if you could document that version 0.6.5 and greater require react-dom v0.14.0. This way if you're using React v0.13.0 you know to use <= 0.6.4.

**Comment by dschoon** [comment]
It'd also be nice if future breaking changes like this didn't happen in a minor release version bump.

Thanks for everything you've done with the library! I don't mean to sound unappreciative, just wanted to provide feedback :smile:

**Comment by felixrieseberg** [comment]
Hey, my bad - you're totally right. I sadly can't fix it (I can't republish on npm), but thanks for telling me that I messed up `semver` - I'll add a line to the readme!

**Comment by felixrieseberg** [comment]
Actually, I believe that the current solution is okay - I unpublished 0.6.5 on npm, meaning that ^0.7 needs React-Dom, while ^0.6 doesn't. Again, thanks for letting me know!

**Comment by dschoon** [comment]
Excellent! Thank you
