### ISSUE TITLE
How to preload images?

### ISSUE THREAD

**Issue by tc** [felixrieseberg/React-Dropzone-Component#6]
Is there a way for this component to expose the dropzone object so i can call ``myDropzone.emit("thumbnail", mockFile, "/image/url");`` to preload images?

See  https://github.com/enyo/dropzone/wiki/FAQ#how-to-show-files-already-stored-on-server

**Comment by felixrieseberg** [comment]
Not yet, but I'm more than happy to include a callback as soon as the `dropzone` is initialized. I'll add that right away :+1:

**Comment by felixrieseberg** [comment]
The `eventHandlers` can now contain a handler for `init`, which will be called when the `dropzone` object is initialized, passing the dropzone as a the first argument. 

I hope this works for you. I'm closing this for now, but feel free to reopen if it doesn't!

**Comment by tc** [comment]
great, will you push a release to npm with this soon?

**Comment by felixrieseberg** [comment]
Already pushed :rocket:

**Comment by aseroj** [comment]
Hi All,
I can not preload images while inside `init`, now the init methods first parameter returns `Dropzone` object thanks to @felixrieseberg, but i can not seem to be call `createThumbnailFromUrl` method.

@tc did you find a solution for this ? if so, can you share ?

thanks

**Comment by tc** [comment]
@aseroj  This might help:

```
    render() {
        return <DropzoneComponent
            config={this.createConfig()}
            eventHandlers={this.eventHandlers()}
            djsConfig={this.createDjsConfig()}
        />;
```


```
    eventHandlers() {
        var self = this;

        return {
            init: function (dropzone) {
                Dropzone.autoDiscover = false;
                self.preloadImages(dropzone);
            },
            removedfile: self.handleRemoveUpload,
            error: self.handleErrorUpload,
            success: self.handleSuccessUpload
        };
    }

    preloadImages(dropzone) {
        (this.props.images || []).forEach( function (i) {
            var name = path.basename(i.url);
            var file = { url: i.url, name: name };
            var width = 100;
            var height = 100;
            var imageUrl = ImageService.resize(i.url, width, height);

            dropzone.emit("addedfile", file);
            dropzone.emit("thumbnail", file, imageUrl);
            dropzone.emit("complete", file);
        });
    }
```

**Comment by aseroj** [comment]
@tc sorry for late response, works perfectly.
any idea how can i pass `Authorization` headers with request ?
