### ISSUE TITLE
Example project is broken

### ISSUE THREAD

**Issue by ewal** [felixrieseberg/React-Dropzone-Component#62]
I'm trying to run the project on my local machine but the example project seems misconfigured. The route /example doesn't exist. As a minor detail, the link in index.html points to port 8000,

regards - Emil

**Comment by Maggieryder** [comment]
Having the same problem. Keep getting 405 error. I'm a bit of a newbie, so just trying to figure out how to send files through Reflux store for processing...???

**Comment by felixrieseberg** [comment]
Hey, thanks for letting me know - the example was indeed broken, I just fixed it. Again, thanks!
