### ISSUE TITLE
why do library sends cache-control header ?

### ISSUE THREAD

**Issue by igorizr1** [felixrieseberg/React-Dropzone-Component#65]
This is the request header:
Access-Control-Request-Headers:accept, cache-control, content-type, x-requested-with

Why does library actually asks for cache-control?

**Comment by felixrieseberg** [comment]
Hey, we don't actually do that - that's something done over in Dropzone.js. I recommend checking for that over there (https://github.com/enyo/dropzone).

I'm closing this in the meantime, because we can't change anything.
