### ISSUE TITLE
JSX Configuration

### ISSUE THREAD

**Issue by akoskm** [felixrieseberg/React-Dropzone-Component#67]
Is there any way to configure this plugin in the JSX fashion. Something like:

```js
render() {
  let callbackArray = [
    function () {
      console.log('Look Ma, I\'m a callback in an array!');
    },
    function () {
      console.log('Wooooow!');
    }
  ];
  let eventHandlers = {
    // All of these receive the event as first parameter:
    drop: callbackArray
  };
  let componentConfig = {
    iconFiletypes: ['.jpg', '.png', '.gif'],
    showFiletypeIcon: true,
    postUrl: '/api/profile/img'
  };

  let djsConfig = {
    addRemoveLinks: true,
    acceptedFiles: 'image/jpeg,image/png,image/gif'
  };

  return (
    <div>
      <DropzoneComponent djsConfig={djsConfig}
        dropzoneConfig={componentConfig}
        eventHandlers={eventHandlers}
    />
    </div>
  );
}
```

I'm getting the following error message when initializing the component:

```
2016-05-03 17:44:23.769 dropzone.js?6517:440 Uncaught Error: No URL provided.
```

**EDIT** I found no examples showing how to configure the component in JSX so I followed https://github.com/felixrieseberg/React-Dropzone-Component/issues/26#issue-106253414

**Comment by felixrieseberg** [comment]
I added examples that show how to use the component with JSX - it should make the usage a bit more clear :eyes:. Check out the `examples` folder!

(Also, sorry that this took literally forever).
