### ISSUE TITLE
No URL Provided error

### ISSUE THREAD

**Issue by dwightware4** [felixrieseberg/React-Dropzone-Component#68]
The readme here says that in order to handle the actually uploading manually (which I need to do), I can just initialize the component with no `postUrl` option set...however this causes the component to crash my app with the following error messages: `Neither postUrl nor a "drop" eventHandler specified, the React-Dropzone component might misbehave.` and `Uncaught Error: No URL provided. dropzone.js:440`

**Comment by felixrieseberg** [comment]
I updated the `README` as well as the examples with a more detailed tutorial on how to process uploads yourself. I hope this answers your issue - feel free to come back with more questions.

If you want to use this component without posting automatically to a URL but instead do the posting yourself, then you can just fill the `postUrl` option with a meaningless string and handle the displaying of progress by yourself using the provided event handlers. To see this in action, check it out [here](https://github.com/felixrieseberg/React-Dropzone-Component/blob/master/example/src/example_no_post_url.jsx)!

```
var componentConfig = { postUrl: 'no-url' };
var djsConfig = { autoProcessQueue: false }
var eventHandlers = { addedfile: (file) => console.log(file) }

ReactDOM.render(
    <DropzoneComponent config={componentConfig}
                       eventHandlers={eventHandlers}
                       djsConfig={djsConfig} />,
    document.getElementById('content')
);

Also, sorry that this took literally forever. Thank you for giving this component a shot!
