### ISSUE TITLE
DOMPropertyOperations.js?930e:153 Error: <polygon> When unmounting

### ISSUE THREAD

**Issue by chrischen** [felixrieseberg/React-Dropzone-Component#71]
When React-Router navigates to a new page and unmounts everything, this error is thrown:

`DOMPropertyOperations.js?930e:153 Error: <polygon> attribute points: Expected number, "NaN NaN, NaN NaN…".`

When it goes back and remounts it and you edit the crop by moving it, it causes
`VM218260:12612 Uncaught Invariant Violation: A state mutation was detected between dispatches, in the path`

**Comment by felixrieseberg** [comment]
We're not using <polygon>, so I'm closing this.
