### ISSUE TITLE
Uploads stuck for files larger than 1MB

### ISSUE THREAD

**Issue by adamwan92** [felixrieseberg/React-Dropzone-Component#72]
Not sure why this is happening, but I can't seem to upload anything bigger than 2MB. It just gets stuck at uploading and won't move. Smaller files work brilliantly.

Please help.

**Comment by marhyorh** [comment]
Mine works fine.

**Comment by felixrieseberg** [comment]
Yeah this is probably not an issue with Dropzone. I'd recommend consulting the dropzone server guide http://www.dropzonejs.com/#server-side-implementation

**Comment by ehssamimi** [comment]
> Not sure why this is happening, but I can't seem to upload anything bigger than 2MB. It just gets stuck at uploading and won't move. Smaller files work brilliantly.
> 
> Please help.

you must increase your timeOut in dropzone frontend confige :
ex:     maxFilesize: 2000,
            timeout:30000000,
