### ISSUE TITLE
Server Side: Multer Issue 

### ISSUE THREAD

**Issue by marhyorh** [felixrieseberg/React-Dropzone-Component#73]
Not working for multer higher than Version 0.1.8

**Comment by marhyorh** [comment]
I fixed it. The code is much different from the examples'.

**Comment by TheBong91** [comment]
could you elaborate? having similar issues

**Comment by marhyorh** [comment]
@TheBong91 The Previous multer, which is version 0.1.8 has a different implementation which the previous example used. If you're following that example, you'll have to downgrade your multer version to 0.1.8 to make the code work and if you're rocking the new multer v1.1.0, just remove all of your previous codes and head on to the new multer example [here](https://github.com/felixrieseberg/React-Dropzone-Component/tree/master/example).
