### ISSUE TITLE
Custom preview link should take you to the Layout section in dz documentation

### ISSUE THREAD

**Issue by StJohn3D** [felixrieseberg/React-Dropzone-Component#76]
The link should point to [http://www.dropzonejs.com/**#layout**](http://www.dropzonejs.com/#layout).
As a user I expect reference links to take me to the relevant peace of information. Just going to the main page confused me and it took a few minutes to find what I was looking for. To save future users some time I'm suggesting the following change to the documentation.

...
##### Custom Preview Template
The djsconfig property is compatible with all of the options in the official [DropzoneJS documentation](http://www.dropzonejs.com/#layout). Updating the preview template can be done as follows:
...

**Comment by felixrieseberg** [comment]
Fair point - done!
