### ISSUE TITLE
Customize body

### ISSUE THREAD

**Issue by kennetpostigo** [felixrieseberg/React-Dropzone-Component#78]
I'm using your dropzone component (which is AWESOME) and I wanted to know if there is anyway to add parameters for body that are sent in the request when a image is dropped.

Code might make more sense:
```js
// Config as it stands
  var componentConfig = {
      iconFiletypes: ['.jpg', '.png', '.gif'],
      showFiletypeIcon: false,
      postUrl: 'http://localhost:8080/uploadUserImage/'
  };

// potential Config for adding to body sent to server
  var componentConfig = {
      iconFiletypes: ['.jpg', '.png', '.gif'],
      showFiletypeIcon: false,
      postUrl: 'http://localhost:8080/uploadUserImage/',
      req : {...}     // <--- Object for data wanting to be sent with image dropping in.
  }
```
Would this be something that could possibly be added to the `componentConfig`?
Currently images are sent but I'd like to be able to send data so that I can dynamically set
the folders that `multer` should place the uploaded images. Say a user uploads an image I'd like to specify where that users folder is to place their profile picture. Something like this:
```js
  var componentConfig = {
      iconFiletypes: ['.jpg', '.png', '.gif'],
      showFiletypeIcon: false,
      postUrl: 'http://localhost:8080/uploadUserImage/',
      req : {
       userId: props.user.id
      }
  }
```

**Comment by ananddodia** [comment]
Hey @kennetpostigo 
did you found any solution to this issue? Even i am facing same issue.

**Comment by kennetpostigo** [comment]
I switched to another component that was simpler to get this working: 
https://github.com/felixrieseberg/React-Dropzone-Component
