### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by frogbandit** [felixrieseberg/React-Dropzone-Component#79]
Using the code `postUrl: '/uploadHandler'` gives me a 405 error on the POST request. How do I fix this?

**Comment by dvwright** [comment]
For a simple case, using the defaults, you need to provide a valid endpoint which accepts an HTTP POST with name 'file'. 

For example (php):

http://yourserver.php/file_upload 

which would have something like:
<code>
if(isset($_POST["submit"])) {
    upload_file = $_FILES["file"]["tmp_name"];
<code>
