### ISSUE TITLE
How to handle upload response?

### ISSUE THREAD

**Issue by sandysaders** [felixrieseberg/React-Dropzone-Component#82]
I want to handle the response from the server, however I can't seem to find out how to get the response back from the `<DropzoneComponent/>` upload request. I want to be able to grab the response or pass a callback that will fire when the response from the server hits the client.

**Comment by civet** [comment]
@sandysaders I just looked into the source code. You can handle the 'success' event to get the response.

```
var eventHandlers = {
  success: function(file, response, error) {
    console.log(response);
  }
};

<DropzoneComponent eventHandlers={eventHandlers} ...
```

**Comment by sandysaders** [comment]
you sure thats not the dropping of the component @civet ?

**Comment by felixrieseberg** [comment]
@civet is absolutely right, that's the correct event handler. It gets the server response as second argument (this event was called finished previously).
