### ISSUE TITLE
Make the whole body a dropzone

### ISSUE THREAD

**Issue by jessica-pixvana** [felixrieseberg/React-Dropzone-Component#86]
I'd like to make the whole body a dropzone as in this page:
https://github.com/enyo/dropzone/wiki/Make-the-whole-body-a-dropzone

Can this be done?

**Comment by felixrieseberg** [comment]
Sorry, not with this module - React needs something to render into, and in this case, a `div` (or something similar) that takes up the whole `body` is the closest that would be possible...

**Comment by jessica-pixvana** [comment]
How would I do it with a large div?

**Comment by felixrieseberg** [comment]
```
<body>
  <Dropzone>
</body>
```

From there, it's just a styling issue, unless you have other reasons to use the whole `body`.
