### ISSUE TITLE
Manual processing with client-side js

### ISSUE THREAD

**Issue by sandervanhooft** [felixrieseberg/React-Dropzone-Component#87]
How can I manually process the files using client-side js? I.e. the `onDrop` prop of `react-dropzone` ([alternative](https://github.com/okonet/react-dropzone) to `react-dropzone-component`). I prefer `react-dropzone-component` for its surplus of config options.

It seems I cannot use the `action` prop for this, as it is used for the form action, not for binding a js function.

**Comment by felixrieseberg** [comment]
I updated the `README` as well as the examples with a more detailed tutorial on how to process uploads yourself. I hope this answers your issue - feel free to come back with more questions.

If you want to use this component without posting automatically to a URL but instead do the posting yourself, then you can just fill the `postUrl` option with a meaningless string and handle the displaying of progress by yourself using the provided event handlers. To see this in action, check it out [here](https://github.com/felixrieseberg/React-Dropzone-Component/blob/master/example/src/example_no_post_url.jsx)!

```
var componentConfig = { postUrl: 'no-url' };
var djsConfig = { autoProcessQueue: false }
var eventHandlers = { addedfile: (file) => console.log(file) }

ReactDOM.render(
    <DropzoneComponent config={componentConfig}
                       eventHandlers={eventHandlers}
                       djsConfig={djsConfig} />,
    document.getElementById('content')
);

Also, sorry that this took literally forever. Thank you for giving this component a shot!

**Comment by sandervanhooft** [comment]
@felixrieseberg Thanks! This may also be relevant for #50 .
