### ISSUE TITLE
Dropzone already attached

### ISSUE THREAD

**Issue by cristianrosu** [felixrieseberg/React-Dropzone-Component#94]
I'm getting `Error: Dropzone already attached.` while trying to render the component. Could not find any info on this when using dropzone with react. Anyone had this issue and managed to fix it?

**Comment by giocodes** [comment]
Despite the fact that this wrapper uses ` Dropzone.autoDiscover = false` I was getting this error while using multiple instances of the component on the same view. 
I noticed that it was only happening while using a custom template `previewTemplate` and the `dropzoneSelector` option. 
I solved this by using a unique ID that is generated on runtime at each component mount:

```javascript
const uniqueId = 'dzjs-' + Date.now().toString();
const componentConfig = {
    // your other options ...
    dropzoneSelector: `#${uniqueId}`,
  };
// use same id on the target element
return(
<div id={uniqueId}>
)
```

**Comment by ali-wells** [comment]
I was running into this too but couldn't use the above uniqueId fix as I was attaching my dropzoneSelector to the body tag for a full screen dropzone. I followed the example on the README to access the dropzone object and hooked up the destroy method to be called via the useEffect hook. Hope it helps someone else who has a similar issue.

```
let myDropzone;

function initCallback(e) {
  myDropzone = dropzone;
}

//Bind this to the eventHandlers prop on the DropzoneComponent
const eventHandlers = {
  init: (e) => {
    initCallback(e);
  }
};

useEffect(() => {
  return () => {
    if (myDropzone) {
      myDropzone.destroy();
    }
  };
}, []);
```

**Comment by DaxStrife** [comment]
I solved it using this.

import Dropzone from "dropzone";

const init = (el, props) => {
  try {
    Dropzone.autoDiscover = false;
    el.dropzone = new Dropzone(el, props.options);
  } catch (error) { }
};

export { init };
