### ISSUE TITLE
Preview key on file object?

### ISSUE THREAD

**Issue by josh91hickman** [felixrieseberg/React-Dropzone-Component#97]
Hello, first and foremost thanks for the great package!

I'm wondering if it is possible to get access to a "preview" key on the file object that I can use for latency compensation? Basically i have a function that is being called on the "addedfile" event listener. I'm then just console.logging the file and I get an object that looks like this.

![screen shot 2016-11-01 at 10 21 32 pm](https://cloud.githubusercontent.com/assets/15853188/19917597/c509b31e-a081-11e6-81af-11aaf1b5f258.png)

Before, I was using [react-dropzone](https://github.com/okonet/react-dropzone) and running the file through the same function I get an array that lists a preview url (for latency compensation). See photo below

![screen shot 2016-11-01 at 10 17 29 pm](https://cloud.githubusercontent.com/assets/15853188/19917617/fbcc86ba-a081-11e6-9396-d57d69c3a93f.png)

Is there a way to access the "preview" key using React-Dropzone-Component

``` javascript
  onDrop(files) {

    console.log(files);
    return;
}

....

 const eventHandlers = {
      addedfile: this.onDrop.bind(this)
    }

**Comment by timotei** [comment]
Bump :)

It seems the only way I found this to work (for now), is for the server to return you in the response the url of the uploaded image. That way you can preview it properly.

However, it's super sad that we can't use it directly :( - I wish I could look into it myself... (but don't have time now)
