### ISSUE TITLE
Error when file upload starts

### ISSUE THREAD

**Issue by ananddodia** [felixrieseberg/React-Dropzone-Component#99]
I am using this plugin in local project running on localhost URL.

In config postUrl parameter is having staging URL to upload a file. That URL is already having CORS enabled and it is already used in other projects. So no issue on server side file upload service.

But when I select image to upload file. It shows error in console.
Error: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.

I also tried modifiying the request header parameter "Access-Control-Request-Headers" using header key in djsConfig props of DropzoneComponent. But still it adds "Access-Control-Request-Headers: cache-control, x-requested-with".(see in attached screenshot)
![dropzone](https://cloud.githubusercontent.com/assets/18732817/20052195/e8bc166e-a4f8-11e6-8135-ec4f1c63bea5.png)

This plugin is much useful to me. Please provide solution to this error.
Thanks.

**Comment by markus-wi** [comment]
Seems like your server is denying the `cache-control` header. Adding the header to your request is not going to solve your problem. In fact, you're just re-doing what your server won't accept. 

Try adding `cache-control` to the `Access-Control-Allow-Headers` **response** header in your server-side code. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers for more infos.

**Comment by forgic** [comment]
thank you
